### ISSUE TITLE
Social media links are linked correctly in the menu bar.

### ISSUE THREAD

**Issue by ashwaniYDV** [Celesta-IITP/Celesta2k19-Webpage#206]
![Annotation 2019-10-12 134522](https://user-images.githubusercontent.com/43786728/66697805-948eb080-ecf6-11e9-9838-d2a34f2a9f40.png)

**Comment by ashwaniYDV** [comment]
@Avinashhaujpura Can you solve this issue? I want you to add the correct links of celesta FB, Insta etc pages here.

**Comment by Avinashhaujpura** [comment]
@ashwaniYDV i have corrected few of them and i am trying

**Comment by Avinashhaujpura** [comment]
i am interested and working

**Comment by Ankit7Das** [comment]
I am interested and I'm working on it
