### ISSUE TITLE
Change all the texts of (connect) or (get in touch) to (Contact Us)

### ISSUE THREAD

**Issue by ashwaniYDV** [Celesta-IITP/Celesta2k19-Webpage#208]
![Annotation 2019-10-12 134908](https://user-images.githubusercontent.com/43786728/66697897-36ae9880-ecf7-11e9-9cac-e544261ecf56.png)
![Annotation 2019-10-12 135056](https://user-images.githubusercontent.com/43786728/66697921-5a71de80-ecf7-11e9-9882-5ca140b60b3b.png)
![Annotation 2019-10-12 135130](https://user-images.githubusercontent.com/43786728/66697930-71183580-ecf7-11e9-9f19-0f791a4f540a.png)

**Comment by Mehulipal** [comment]
I want to try

**Comment by ashwaniYDV** [comment]
@Mehulipal Go on!
