### ISSUE TITLE
In events full image is not showing 

### ISSUE THREAD

**Issue by Avinashhaujpura** [Celesta-IITP/Celesta2k19-Webpage#209]
![IMG_20191012_144853](https://user-images.githubusercontent.com/54908795/66698927-37afdd80-ec97-11e9-8cc8-ccc3ed1a9702.jpg)

**Comment by atm1504** [comment]
@Avinashhaujpura please elaborate this issue?
The image was meant to display that portion of the screen only. Also, thats the entire image that is displayed there.

**Comment by Rohankumar2804** [comment]
<html>
    <head><style>img.bg {
    min-height: 100%;
    min-width: 1024px;
    width: 100%;
    height: auto;
    position: fixed;
    top: 0;
    left: 0;
}

@media screen and (max-width: 1024px){
    img.bg {
    left: 50%;
    margin-left: -512px; }
}
        </style>
    </head>
    <body><img src="

![](https://user-images.githubusercontent.com/54908795/66698927-37afdd80-ec97-11e9-8cc8-ccc3ed1a9702.jpg)
" alt="background" class="bg" />
    </body>
</html>
